#!/bin/bash

# Script to create comprehensive language files for admin dashboard
# This will generate Arabic and Farsi translations

echo "Creating comprehensive language files..."

# Create Arabic translations
cat > apps/admin/dist/locales/ar.json << 'EOF'
{
  "common": {
    "dashboard": "لوحة القيادة",
    "stations": "المحطات",
    "users": "المستخدمون",
    "charging_sessions": "جلسات الشحن",
    "payments": "المدفوعات",
    "analytics": "التحليلات",
    "reports": "التقارير",
    "notifications": "الإشعارات",
    "support": "الدعم",
    "settings": "الإعدادات",
    "language": "اللغة",
    "english": "الإنجليزية",
    "arabic": "العربية",
    "farsi": "الفارسية",
    "search": "بحث",
    "filter": "تصفية",
    "export": "تصدير",
    "import": "استيراد",
    "add_new": "إضافة جديد",
    "edit": "تعديل",
    "delete": "حذف",
    "view_details": "عرض التفاصيل",
    "save": "حفظ",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "close": "إغلاق",
    "back": "رجوع",
    "next": "التالي",
    "previous": "السابق",
    "loading": "جاري التحميل",
    "no_data": "لا توجد بيانات متاحة",
    "error": "خطأ",
    "success": "نجح",
    "warning": "تحذير",
    "info": "معلومات",
    "active": "نشط",
    "inactive": "غير نشط",
    "pending": "معلق",
    "completed": "مكتمل",
    "cancelled": "ملغى",
    "failed": "فشل",
    "total": "المجموع",
    "average": "المتوسط",
    "maximum": "الحد الأقصى",
    "minimum": "الحد الأدنى",
    "date": "التاريخ",
    "time": "الوقت",
    "duration": "المدة",
    "status": "الحالة",
    "actions": "الإجراءات",
    "refresh": "تحديث",
    "download": "تحميل",
    "print": "طباعة",
    "share": "مشاركة"
  },
  "dashboard": {
    "title": "لوحة القيادة",
    "welcome_message": "مرحباً بك في منصة شحن المركبات الكهربائية",
    "overview": "نظرة عامة",
    "total_stations": "إجمالي المحطات",
    "active_stations": "المحطات النشطة",
    "total_users": "إجمالي المستخدمين",
    "active_users": "المستخدمون النشطون",
    "total_sessions": "إجمالي الجلسات",
    "active_sessions": "الجلسات النشطة",
    "total_revenue": "إجمالي الإيرادات",
    "monthly_revenue": "الإيرادات الشهرية",
    "energy_consumed": "الطاقة المستهلكة",
    "co2_saved": "ثاني أكسيد الكربون الموفور",
    "recent_activity": "النشاط الأخير",
    "system_health": "صحة النظام",
    "performance_metrics": "مقاييس الأداء",
    "quick_actions": "الإجراءات السريعة",
    "view_all": "عرض الكل"
  },
  "stations": {
    "title": "إدارة المحطات",
    "station_id": "معرف المحطة",
    "station_name": "اسم المحطة",
    "location": "الموقع",
    "address": "العنوان",
    "city": "المدينة",
    "state": "الولاية",
    "country": "البلد",
    "postal_code": "الرمز البريدي",
    "latitude": "خط العرض",
    "longitude": "خط الطول",
    "operator": "المشغل",
    "connectors": "الموصلات",
    "connector_type": "نوع الموصل",
    "power_kw": "الطاقة (كيلوواط)",
    "voltage": "الجهد",
    "current": "التيار",
    "availability": "التوفر",
    "pricing": "التسعير",
    "price_per_kwh": "السعر لكل كيلوواط ساعة",
    "parking_fee": "رسوم الوقوف",
    "amenities": "المرافق",
    "wifi": "واي فاي",
    "restroom": "دورة مياه",
    "food": "طعام",
    "shopping": "تسوق",
    "parking": "وقوف",
    "accessibility": "إمكانية الوصول",
    "wheelchair_accessible": "متاح للكراسي المتحركة",
    "operating_hours": "ساعات العمل",
    "open_24_7": "مفتوح 24/7",
    "maintenance": "الصيانة",
    "last_maintenance": "آخر صيانة",
    "next_maintenance": "الصيانة التالية",
    "maintenance_status": "حالة الصيانة",
    "add_station": "إضافة محطة",
    "edit_station": "تعديل المحطة",
    "station_details": "تفاصيل المحطة",
    "connector_details": "تفاصيل الموصل",
    "search_stations": "البحث عن المحطات...",
    "filter_by_location": "تصفية حسب الموقع",
    "filter_by_operator": "تصفية حسب المشغل",
    "filter_by_status": "تصفية حسب الحالة",
    "all_locations": "جميع المواقع",
    "all_operators": "جميع المشغلين",
    "all_statuses": "جميع الحالات",
    "online": "متصل",
    "offline": "غير متصل",
    "maintenance_mode": "وضع الصيانة",
    "no_stations_found": "لم يتم العثور على محطات.",
    "station_statistics": "إحصائيات المحطات",
    "total_connectors": "إجمالي الموصلات",
    "available_connectors": "الموصلات المتاحة",
    "occupied_connectors": "الموصلات المشغولة",
    "out_of_order": "خارج الخدمة",
    "station_performance": "أداء المحطة",
    "utilization_rate": "معدل الاستخدام",
    "average_session_duration": "متوسط مدة الجلسة",
    "revenue_generated": "الإيرادات المُولدة",
    "energy_delivered": "الطاقة المُسلمة"
  }
}
EOF

# Create Farsi translations
cat > apps/admin/dist/locales/fa.json << 'EOF'
{
  "common": {
    "dashboard": "داشبورد",
    "stations": "ایستگاه‌ها",
    "users": "کاربران",
    "charging_sessions": "جلسات شارژ",
    "payments": "پرداخت‌ها",
    "analytics": "تحلیل‌ها",
    "reports": "گزارش‌ها",
    "notifications": "اعلان‌ها",
    "support": "پشتیبانی",
    "settings": "تنظیمات",
    "language": "زبان",
    "english": "انگلیسی",
    "arabic": "عربی",
    "farsi": "فارسی",
    "search": "جستجو",
    "filter": "فیلتر",
    "export": "خروجی",
    "import": "ورودی",
    "add_new": "افزودن جدید",
    "edit": "ویرایش",
    "delete": "حذف",
    "view_details": "مشاهده جزئیات",
    "save": "ذخیره",
    "cancel": "لغو",
    "confirm": "تأیید",
    "close": "بستن",
    "back": "بازگشت",
    "next": "بعدی",
    "previous": "قبلی",
    "loading": "در حال بارگذاری",
    "no_data": "داده‌ای موجود نیست",
    "error": "خطا",
    "success": "موفق",
    "warning": "هشدار",
    "info": "اطلاعات",
    "active": "فعال",
    "inactive": "غیرفعال",
    "pending": "در انتظار",
    "completed": "تکمیل شده",
    "cancelled": "لغو شده",
    "failed": "ناموفق",
    "total": "کل",
    "average": "میانگین",
    "maximum": "حداکثر",
    "minimum": "حداقل",
    "date": "تاریخ",
    "time": "زمان",
    "duration": "مدت زمان",
    "status": "وضعیت",
    "actions": "عملیات",
    "refresh": "تازه‌سازی",
    "download": "دانلود",
    "print": "چاپ",
    "share": "اشتراک"
  },
  "dashboard": {
    "title": "داشبورد",
    "welcome_message": "به پلتفرم شارژ خودروهای برقی خوش آمدید",
    "overview": "نمای کلی",
    "total_stations": "کل ایستگاه‌ها",
    "active_stations": "ایستگاه‌های فعال",
    "total_users": "کل کاربران",
    "active_users": "کاربران فعال",
    "total_sessions": "کل جلسات",
    "active_sessions": "جلسات فعال",
    "total_revenue": "کل درآمد",
    "monthly_revenue": "درآمد ماهانه",
    "energy_consumed": "انرژی مصرف شده",
    "co2_saved": "CO2 صرفه‌جویی شده",
    "recent_activity": "فعالیت اخیر",
    "system_health": "سلامت سیستم",
    "performance_metrics": "معیارهای عملکرد",
    "quick_actions": "عملیات سریع",
    "view_all": "مشاهده همه"
  },
  "stations": {
    "title": "مدیریت ایستگاه‌ها",
    "station_id": "شناسه ایستگاه",
    "station_name": "نام ایستگاه",
    "location": "موقعیت",
    "address": "آدرس",
    "city": "شهر",
    "state": "استان",
    "country": "کشور",
    "postal_code": "کد پستی",
    "latitude": "عرض جغرافیایی",
    "longitude": "طول جغرافیایی",
    "operator": "اپراتور",
    "connectors": "کانکتورها",
    "connector_type": "نوع کانکتور",
    "power_kw": "توان (کیلووات)",
    "voltage": "ولتاژ",
    "current": "جریان",
    "availability": "در دسترس بودن",
    "pricing": "قیمت‌گذاری",
    "price_per_kwh": "قیمت هر کیلووات ساعت",
    "parking_fee": "هزینه پارکینگ",
    "amenities": "امکانات",
    "wifi": "وای‌فای",
    "restroom": "سرویس بهداشتی",
    "food": "غذا",
    "shopping": "خرید",
    "parking": "پارکینگ",
    "accessibility": "دسترسی",
    "wheelchair_accessible": "دسترسی ویلچر",
    "operating_hours": "ساعات کاری",
    "open_24_7": "24/7 باز",
    "maintenance": "نگهداری",
    "last_maintenance": "آخرین نگهداری",
    "next_maintenance": "نگهداری بعدی",
    "maintenance_status": "وضعیت نگهداری",
    "add_station": "افزودن ایستگاه",
    "edit_station": "ویرایش ایستگاه",
    "station_details": "جزئیات ایستگاه",
    "connector_details": "جزئیات کانکتور",
    "search_stations": "جستجوی ایستگاه‌ها...",
    "filter_by_location": "فیلتر بر اساس موقعیت",
    "filter_by_operator": "فیلتر بر اساس اپراتور",
    "filter_by_status": "فیلتر بر اساس وضعیت",
    "all_locations": "همه موقعیت‌ها",
    "all_operators": "همه اپراتورها",
    "all_statuses": "همه وضعیت‌ها",
    "online": "آنلاین",
    "offline": "آفلاین",
    "maintenance_mode": "حالت نگهداری",
    "no_stations_found": "هیچ ایستگاهی یافت نشد.",
    "station_statistics": "آمار ایستگاه‌ها",
    "total_connectors": "کل کانکتورها",
    "available_connectors": "کانکتورهای موجود",
    "occupied_connectors": "کانکتورهای اشغال شده",
    "out_of_order": "خراب",
    "station_performance": "عملکرد ایستگاه",
    "utilization_rate": "نرخ استفاده",
    "average_session_duration": "میانگین مدت جلسه",
    "revenue_generated": "درآمد تولید شده",
    "energy_delivered": "انرژی تحویل داده شده"
  }
}
EOF

echo "Language files created successfully!"
echo "Files created:"
echo "- apps/admin/dist/locales/en.json (English)"
echo "- apps/admin/dist/locales/ar.json (Arabic)"
echo "- apps/admin/dist/locales/fa.json (Farsi)"
echo ""
echo "Next step: Update all HTML pages to use these comprehensive translations"

