name = "ev-charging-token-service"
main = "worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "ev-charging-token-service-production"

[env.staging]
name = "ev-charging-token-service-staging"

# Environment variables
[vars]
SOLANA_NETWORK = "devnet"
SERVICE_VERSION = "1.0.0"

# Secrets (set via wrangler secret put)
# SOLANA_RPC_URL
# MINT_AUTHORITY_PRIVATE_KEY
# EVCH_MINT_ADDRESS
