name = "ev-charging-platform-production"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Database configuration
[[d1_databases]]
binding = "DB"
database_name = "ev-charging-db"
database_id = "29c0c86a-30c6-4a7c-a9b7-4399b3bf02ce"

[vars]
ENVIRONMENT = "production"
