/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [
    'bg-card',
    'text-card-foreground',
    'text-muted-foreground',
    'rounded-lg',
    'shadow-sm',
    'border',
    'bg-background',
    'text-foreground',
    'bg-primary',
    'text-primary-foreground',
    'bg-secondary',
    'text-secondary-foreground',
    'bg-muted',
    'text-muted-foreground',
    'bg-accent',
    'text-accent-foreground',
    'bg-destructive',
    'text-destructive-foreground',
    'bg-popover',
    'text-popover-foreground',
    'border-border',
    'ring-ring',
    'bg-input',
    'rounded-md',
    'rounded-sm',
    'p-6',
    'pt-0',
    'space-y-1.5',
    'flex-col',
    'text-2xl',
    'font-semibold',
    'leading-none',
    'tracking-tight',
    'text-sm',
    'flex',
    'items-center',
    'space-x-2',
    'space-x-3',
    'space-x-4',
    'space-y-2',
    'space-y-4',
    'space-y-6',
    'gap-4',
    'gap-5',
    'gap-6',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'h-4',
    'w-4',
    'h-3',
    'w-3',
    'h-12',
    'w-12',
    'h-64',
    'h-10',
    'w-full',
    'flex-1',
    'flex-shrink-0',
    'min-w-0',
    'text-center',
    'text-xs',
    'text-sm',
    'text-lg',
    'font-medium',
    'font-bold',
    'font-semibold',
    'text-gray-600',
    'text-gray-500',
    'text-gray-400',
    'text-gray-900',
    'text-gray-300',
    'text-red-600',
    'text-red-400',
    'text-blue-600',
    'text-blue-700',
    'text-green-500',
    'text-yellow-500',
    'bg-gray-100',
    'bg-gray-700',
    'bg-blue-600',
    'bg-blue-700',
    'bg-green-500',
    'bg-yellow-500',
    'bg-red-500',
    'border-b-2',
    'border-blue-600',
    'animate-spin',
    'rounded-full',
    'mx-auto',
    'mb-4',
    'mt-4',
    'px-4',
    'py-2',
    'pl-9',
    'pr-3',
    'py-2',
    'px-3',
    'hover:bg-blue-700',
    'hover:underline',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'focus-visible:ring-offset-2',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
    'file:border-0',
    'file:bg-transparent',
    'file:text-sm',
    'file:font-medium',
    'placeholder:text-muted-foreground',
    'ring-offset-background',
    'transition-colors',
    'focus-visible:ring-inset',
    'disabled:pointer-events-none',
    'relative',
    'absolute',
    'left-3',
    'top-1/2',
    '-translate-y-1/2',
    'mr-2',
    'ml-2',
    'mt-1',
    'mt-2',
    'mt-4',
    'mb-2',
    'mb-4',
    'py-12',
    'justify-between',
    'justify-center',
    'items-center',
    'flex-row',
    'flex-col',
    'overflow-y-auto',
    'min-h-screen',
    'container',
    'mx-auto',
    'padding',
    '2rem',
    'screens',
    '2xl',
    '1400px',
    'center',
    'true',
    'z-10',
    'z-50',
    'top-1/2',
    'fixed',
    'sticky',
    'block',
    'hidden',
    'inline',
    'inline-flex',
    'h-[300px]',
    'flex-1',
    'flex-shrink-0',
    '-translate-y-1/2',
    'grid-cols-1',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-between',
    'justify-center',
    'overflow-y-auto',
    'rounded-full',
    'border',
    'border-r',
    'border-b',
    'border-b-2',
    'border-transparent',
    'text-center',
    'leading-none',
    'whitespace-nowrap',
    'capitalize',
    'underline-offset-4',
    'ring',
    'outline',
    'filter',
    'transition-colors',
    'file:border-0',
    'file:bg-transparent',
    'hover:underline',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:outline-none',
    'focus:ring-inset',
    'focus-visible:ring-2',
    'focus-visible:ring-offset-2',
    'focus-visible:outline-none',
    'disabled:pointer-events-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50'
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
